name: check
on:
  pull_request_target:
permissions: {}
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.read-input.outputs.ref }}
          repository: ${{ steps.read-input.outputs.head_repo || github.repository }}

      - run: | 
          echo "wworked"


      - run: |
          echo "chain-a ran for ${{ github.event.pull_request.head.repo.full_name }} @ ${{ github.event.pull_request.head.ref }}"

